phoenix-inst-chat-7b:
    config_dir: FreedomIntelligence/phoenix-inst-chat-7b
    model_id: 'phoenix-inst-chat-7b'
    prompt: "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.\n\nHuman: <s>{question}</s>Assistant: <s>"
    generation_config:
        # max_length: 2048          
        max_new_tokens: 156     
        min_length: 10          
        min_new_tokens: 0       
        early_stopping: False   
        do_sample: True         
        temperature: 0.7        
        top_k: 50               
        top_p: 1.0              
        repetition_penalty: 1.0 
        no_repeat_ngram_size: 0 
    
    batch_size: 10
    device: 'cuda'          # ['cuda', 'cpu', 'mps']
    n_gpus: 1               # int>0, or 'auto'
    precision: 'fp16'
    answer_id: 'auto'
    input_pth: 'data/zhenge/zhenge_all.jsonl'
    output_dir_or_file: 'output/zhenge'
#######################################